### ISSUE TITLE
Any yolov5m medium config for training from scratch?

### ISSUE THREAD

**Issue by sarmientoj24** [cv516Buaa/tph-yolov5#6]
All configs are for large as I can see it

**Comment by cv516Buaa** [comment]
I don’t know if yolov5m will have a good result, because I have never used it.
If you want to use yolov5m, all you have to do is to modify the 5,6 lines in the yaml file as shown below
```
depth_multiple: 0.67  # model depth multiple
width_multiple: 0.75  # layer channel multiple
```
Our repository is just to provide an example, models can be modified with reference to [yolov5](https://github.com/ultralytics/yolov5)
